#!/bin/bash

alias ea='vi ~/.aliases; source ~/.aliases && echo "aliases sourced  --ok."'
alias eb='vi ~/.bashrc; source ~/.bashrc && echo "bash rc sourced --ok."'
alias ez='vi ~/.zshrc; source ~/.zshrc && echo "zsh sourced --ok."'

alias egrep='LC_ALL=C egrep --color=auto'
alias fgrep='LC_ALL=C fgrep --color=yes'
alias grep='LC_ALL=C grep --color=auto'

alias untar='echo "tar -xzf"; tar -xvf'
alias untarz='echo "tar -vzxf"; tar -vzxf'

alias cls='printf "\033c"'
alias sudo='sudo ' # allow sudo to use aliases
alias ip='ip -c' # use color ip


alias cwd='printf "%q\n" "$(pwd)"'

alias :q='exit'
alias :q!='exit'
alias :wq='exit'
alias :Q='exit'
alias :wq!='exit'

if [[ "$OSTYPE" == "darwin"* ]]; then
	alias ls='ls -G'
else
	alias ls='ls --color=auto'
	alias open='xdg-open'
fi

alias l='ls'

alias proxies="[[ -e $HOME/scripts/aliases/proxies.sh ]] &&	source $HOME/scripts/aliases/proxies.sh"
alias curl-proxies="[[ -e $HOME/scripts/aliases/proxies.sh ]] && source $HOME/scripts/aliases/curl_proxies.sh"

alias curl="[[ -e $HOME/scripts/aliases/curl_proxies.sh ]] && source $HOME/scripts/aliases/curl_proxies.sh; curl"
alias node="[[ -e $HOME/scripts/aliases/curl_proxies.sh ]] && source $HOME/scripts/aliases/curl_proxies.sh; node"
alias npm="[[ -e $HOME/scripts/aliases/curl_proxies.sh ]] && source $HOME/scripts/aliases/curl_proxies.sh; npm"

alias vi='vim'
alias review='vim -c "set list"'
alias mod='stat -c "%a %n"'
alias mode='mod'
alias unpa='[[ -x $HOME/scripts/aliases/unpack_all.sh ]] && $HOME/scripts/aliases/unpack_all.sh'
alias mkdir='mkdir -p'

alias gc='git checkout'
alias gp='git pull'
